### ISSUE TITLE
Can't find info on Multi APs and Managed switches

### ISSUE THREAD

**Issue by gilbreen** [mjp66/Ubiquiti#1]
The description for the Ubiquiti Home Network.pdf states 'Added Multi AP / Managed SW Info.', but I don't seem to be able to find the info in the pdf.  It seems that it is the same version from before, but I am not sure if I am missing it.

Thanks for a great guide!

**Comment by mjp66** [comment]
You are Welcome. These changes were only minor. They approximately were:

Added about page 2:
If your Internet Service Provider’s (ISP) equipment does not provide
an IP address via DHCP, then you will need to adjust your
WAN (eth0) settings after running the setup wizard.
In particular, if you need to use PPPoE, then you might want to read:
https://community.ubnt.com/t5/EdgeMAX/Can-t-open-some-webpages/m-p/1950743/highlight/true#M163311
https://samuel.kadolph.com/2015/02/mtu-and-tcp-mss-when-using-pppoe-2/

Modified about page 14:

When VLANs are used, all devices involved with this data need to be VLAN aware.
Any network switches carrying VLAN traffic will need to be IEEE 802.1Q capable,
e.g. a Level 2 managed switch.

Note that the only VLAN traffic shown in Table 1 - Table of Networks
is involved with the Wi-Fi Guest Network and the Wi-Fi IOT Network.
The Ubiquiti AP-AC-LR access point is VLAN aware.
Eventually the Access Point will be plugged-into
the EdgeRouter’s eth4 interface,
so VLAN data will be able to be carried between them.
This Wi-Fi VLAN data does NOT need to flow to devices on the Wired Home Network.
If you only have one Access Point,
the network switch attached to the EdgeRouter’s
eth3 interface can be (a cheaper) unmanaged switch.
If you are going to deploy multiple Access Points,
then the switch attached to the EdgeRouter’s eth3 interface
MUST be IEEE 802.1Q capable.
Reference Figure 1 - Overview Diagram.
If they are needed, the network switches attached to the EdgeRouter’s
eth1 and/or eth2 interfaces can be (cheaper) unmanaged switches.
