### ISSUE TITLE
VLAN Aware Switches

### ISSUE THREAD

**Issue by MikeWills** [mjp66/Ubiquiti#12]
Do you know of any low-cost VLAN aware switches? Do they need to be configured separately? Would it be less painful to get the Unifi Switches?

**Comment by gilbreen** [comment]
While I haven't finished installing them yet and set up the VLANs, I purchased some TP-Link switches that should be able to work as they VLAN aware.  They can be found for around $38 on Amazon, but I found them on sale at Fry's for $20/each about six weeks ago.  I bought the eight-port model.

https://www.amazon.com/TP-Link-Ethernet-Sheilded-Replacement-TL-SG108E/dp/B00K4DS5KU/ref=sr_1_1?ie=UTF8&qid=1517251713&sr=8-1&keywords=tplink+easy+smart+switch

**Comment by MikeWills** [comment]
Do they need to be configured separately or do they "just work"?

**Comment by mjp66** [comment]
Me guess would be that any managed switch would need configured. See also Issue [https://github.com/mjp66/Ubiquiti/issues/11](https://github.com/mjp66/Ubiquiti/issues/11)

**Comment by gilbreen** [comment]
Out of the box, they can function as an unmanaged switch.  I assigned a static IP address to each one to make it easier.  But, as Mike Potts is correct that managed switches are just that, managed.  You would need to configure each one for your specific use (i.e. VLAN configuration and any other configuration you want to implement).  That is my next step, but haven't gotten there yet.

**Comment by MikeWills** [comment]
Would it be better/easier to get the Unifi Switches? I know they cost more. Here is what I want:

1. A rental network
2. A home network
3. A IOT Wifi network (I really don't have any wired IOT at this time)

I will be getting two UAP-Lites to handle the wifi load in the house (less than 50 devices). I am trying to figure out the switches. I think two unmanaged switches (one off the X and one in my office for wired) and one managed for Wifi. Am I going overkill?

**Comment by gilbreen** [comment]
I haven't used the Unifi switches.  I had to replace 6 switches in my home, so for me it came down to paying $120 for the TP-Link switches or $690 for the Unifi 8 port switches.  I went the less expensive route.

How much square footage/type of construction are you talking about?  We use one UAP-AC-Pro and it covers our 3700 sq foot house (wood studs and drywall).

**Comment by MikeWills** [comment]
About 2700 sq ft. However, in talking to people in the UBNT Facebook Group (https://www.facebook.com/groups/ubntedgeos/), you should plan on about 30-40 wifi devices per WAP. I have over that (not by much). I am going back and forth on going with one, but with a Rental, I think it's better I keep it two to allow for better distribution of load. Plus my office is in the garage. It'd be nice to have something close to there for a stronger signal.

**Comment by mjp66** [comment]
@MikeWills

1.  Is this a single structure / house which has both your family and paying renters in it?
2.  I will presume that you want/need to provide WiFi to the renters.
3.  Do you also want/need to provide wired Ethernet connections to the renters?
3A. If so, do the renter's wired connections need to be on the same Network as the renter's WiFi?
4.  Do the renters want/need to have (access to) a Guest WiFi network for their own guests?
4A. If so, do you care if the renter's guests and your own guests share the same Guest Network?

I am making assumptions about your answers to these questions.
Legal Disclaimer about violating your ISPs terms of service i.e. sharing data / connections ...

I would be more worried about ensuring that your Network and the renters Network be separated by firewall rules than about switches. This is one specific use case for the Wired Separate Network.

See the 1/30/2018 guide for these new sections: '10. About using two or more access points' and '11. Multimedia over Coax Alliance (MOCA)' Also see '28. Add VLAN Networks to the EdgeRouter'.

Remember that Ubiquiti Access Points (UAPs) are capable of supporting four SSIDs, only three were used in the guide. You have another WiFi SSID available.

If 3 is false, and 4A is false: Recover eth1 and/or eth2, connect two UAPs directly to the ER-X, position a UAP in each house area, add a renter SSID and then firewall it off from the Home Network. Give the renters the passwords to the renter SSID and the Guest SSID.

For more wired connections, you can use un-managed switches to connect "regular" equipment to the ER-X. Regular means: not needing access to any VLAN information.

If you are connecting a UAP to a switch, then that switch needs to be an 802.1Q managed switch.  That switch also needs to be specifically configured to pass VLAN information. See 'Figure 1 - Overview Diagram' in the guide.  The specific port used to connect your switch(es) to the ER-X determines what data that switch will see / use.  In the current guide, VLAN information is only needed by UAPs.

I can't help you with switch selection / configuration.

-Mike

**Comment by mjp66** [comment]
@MikeWills @gilbreen @mpegyna Please see guide updates of 2/10/2018 for using an inexpensive managed switch for connecting multiple Ubiquiti Access Points.
