### ISSUE TITLE
corrections

### ISSUE THREAD

**Issue by r0adawg** [mjp66/Ubiquiti#13]
small corrections in : Ubiquiti Home Network.pdf

section 24, if user updates timezone, remind to save this change.
section 52 page 2, description does not match name 'wifi_iot_local'

Thank you for the excellent document!  I really can't wait until I can add an access point to go through the rest of this PDF.

----------------------------
edit: from document dated 01/21/2018

**Comment by chimera451** [comment]
First I would like to say that this guide is awesome! After buying almost the same setup, I did a little googling for help on how to set up the gear and found this. The architecture was exactly what I was trying to achieve so thanks again! I have a few comments from going through the guide:

1. In section 21 about DNS, I'd love to hear your reasoning on why you picked Level3 DNS for the separate network and OpenDNS for IOT and Guest networks.
2. In section 60, if I understand correctly, turning on SmartQueue will turn off the hwnat feature we enabled earlier?
3. I'm very interested in enabling the adblocking features. The linked forum post implies some dnsmasq config needs to be completed but it doesn't seem like you did anything?

Thanks again for an excellent guide. Clearly a lot of effort was put into it!

**Comment by mjp66** [comment]
@r0adawg please send me section 52 details, including document date you were working from, so I can do an update.

@chimera451 DNS: just what I chose at that time, feel free to modify. SmartQueue: unsure, as I only enabled it on the WAN upload (which is not part of the hardware switch.)  AdBlocking: I simply installed and ran the self-test. I didn't dig too deep, as it didn't seem to have any ill effects. Maybe it is not correct or not actually working. Do you have links / details?

**Comment by r0adawg** [comment]
doc date 01/21/2018 page 66

name WIFI_IOT_LOCAL {
default-action drop
description "Wired Iot Local"

description should match name

**Comment by raretrack** [comment]
Thanks for this excellent resource - I've implemented this with an Edge Router X and a Unifi AP-AC-Lite.

Just an update to section 23 (page 30). Quad9 does now have a secondary filtered DNS at 149.112.112.112 - as mentioned by Steve Gibson in Security Now! #640 - https://www.grc.com/sn/sn-640.htm

**Comment by mjp66** [comment]
Guide updated.
