### ISSUE TITLE
Private internet access/VPN connection?

### ISSUE THREAD

**Issue by kyleyoung101** [mjp66/Ubiquiti#15]
So far, I have followed your guide to the letter, up to section 61. Everything seems to work as expected, EXCEPT that while I can connect  to my PIA VPN, it seems to allow no traffic through? I am directly connected to the eth3 port, and have not yet configured wireless; Since I switch it on and off on my computer, I would rather not attempt to set it up for the entire router until I get more experienced with the jargon/understanding.

Have you encountered this at all in your testing? I followed the same DNS rules that you did, but from the log files for the VPN, it seems to attempt to set my local DNS
`d.add ServerAddresses * 209.222.18.222 209.222.18.218
set State:/Network/Service/523422D-D506-4238-A77A-F05F8A5E0271/DNS`

The Ubiquiti forums are full of people trying to get PIA to work with their router, but none seem to address people who just want to allow the connection through.

**Comment by mjp66** [comment]
I have no experience with and have not setup a VPN. 

I suggest you create a Ubiquiti community account and ask them. If you ask the forum, they will probably want you to post your (slightly redacted) ER-X configuration file and/or network map.
Note there are special ways to attach your config file.

If you post, you can reference this github repository as source or not. On that forum I am also "@mjp66". if you reference me in the post, then I can also follow along.

If you get it to work, you can repost the urls / details here, and I will add pointers from the guide to this issue.

Help this helps,
-Mike

**Comment by MikeWills** [comment]
I struggled to get OpenVPN running on the EdgeRouter. I stopped trying and set up a Raspberry Pi instead.
