### ISSUE TITLE
Updated Adblock and Blacklisting package

### ISSUE THREAD

**Issue by raretrack** [mjp66/Ubiquiti#16]
Hi Mike

Just noticed Britannic has a newer and completely rewrote version of the Adblock / Blacklisting package:
https://community.ubnt.com/t5/EdgeMAX/DNS-Adblocking-amp-Blacklisting-dnsmasq-Configuration/td-p/2215008 
https://github.com/britannic/blacklist

I've replaced the old one with this one on my ER-X, seems to be working fine. Up to you, of course, whether you want to update Chapter 72 or not.

**Comment by mjp66** [comment]
Thanks, I have also been watching this version progress. Added a note for now, will test and update the section in a few weeks.
