### ISSUE TITLE
Making source available?

### ISSUE THREAD

**Issue by PaulWalkerUK** [mjp66/Ubiquiti#19]
I really like the idea of what you've done here and I might be interested in making one or two suggestions based on my own setup I've got working. Unfortunately, because the main file is a PDF, GitHub treats it as a binary file which makes it very difficult to diff it to see what's changed in a commit or to submit pull requests.

I wondered if you'd considered uploading the document in a more "diff-friendly" format? If you still wanted to have a PDF for people to download, maybe the PDF could be built and uploaded as a release periodically.

Is the `show configuration commands.txt` script still up to date? I notice it shows as 10 months old, but there have been a number of changes to the PDF file.

One thing I've found useful now I'm version controlling my own config, is to extract at least the `config.boot` file from the `.tar.gz` archive and version control that? It's this that contains the bulk of the configuration (on my setup anyway) - certainly all the interesting stuff! Again, the `.tar.gz` file could be uploaded when making a release.

No worries if you'd prefer to keep it as-is 😄

**Comment by mjp66** [comment]
Content suggestions are welcome.

I had not thought of using a more source-friendly format. I will probably continue to stay with a PDF format for release, as that seems suitable for the most people.

There should be multiple free / open source PDF diff tools available. If nothing else, then try select-all / copy on the different PDF files, paste into different text files and then compare. I have been trying to make the commit messages more descriptive, but space is limited.

One of my all-time favorite programs is Beyond Compare. I have been using it for so long, I forget that other people don't know about it or have it.  [https://www.scootersoftware.com/](url)

I have not been keeping the backup file or the show config data file up to date. I recently added a statement to this effect, to the guide. Reasons are: 1. Way too much regression work. 2. People won't learn, if they simply load and don't participate / follow along / tinker. 3. I'm trying to add new sections and content.

I just version control the entire tar.gz file, as it is not much bigger, and is easier to change / restore between my test ER-X and production ER-X. The entire backup file is also nicely named with a built-in date.

-Mike
