### ISSUE TITLE
Subnet decisions?

### ISSUE THREAD

**Issue by PaulWalkerUK** [mjp66/Ubiquiti#2]
Hi,

Thanks for such a comprehensive guide! I'm only just starting to work through it and am learning some new things as I go, but there's one thing I'm not clear on and wonder if you would mind clarifying for me?

If I understand correctly, the "Wired Home Net" and "Wifi Home Net" are in the same subnet and VLAN so any Home device can communicate with any other Home device (wired or wifi). 

Networks | Wired Home Device | Wifi Home Device
-----------|-----------------------|----------
**Wired Home Device** | Allowed | Allowed
**Wifi Home Device** | Allowed | Allowed

This doesn't appear to be the case for the "Wired IOT Net" and "Wifi IOT Net". They look to be on separate subnets/VLANs. Am I right in thinking that a wired IOT device will be able to communicate with another wired IOT device and a wifi IOT device will be able to communication with another wifi IOT device; but a wired IOT device will not be able to communicate with a wifi IOT device? 

Networks | Wired IOT Device | Wifi IOT Device
-----------|-----------------------|----------
**Wired IOT Device** | Allowed | Disallowed
**Wifi IOT Device** | Disallowed | Allowed

In which case do we essentially have two completely separate IOT networks? If so, is there any particular reason why it's setup this way? Why not put them on the same subnet/VLAN, like the Home Networks?

**Comment by mjp66** [comment]
You are correct, there are two separate WIFi networks.

The WiredHome and WifiHome Networks ARE the same subnet / network. That data is on the trunk (i.e. not a VLAN) when communicated to the Access Point.

You can only have one trunk to the Access Point, and I was not able to figure out how to couple a (wired) subnet which originates from the ER-X, with a (wifi) VLAN which originates from the AP. 

Enjoy and keep learning,
-Mike

**Comment by mjp66** [comment]
Added this as a question on page 32 of the latest revision.
