### ISSUE TITLE
backup file that matches manual

### ISSUE THREAD

**Issue by Scott216** [mjp66/Ubiquiti#21]
I followed the config up to section 64 - setting up UniFi.  When I plugged my UniFi into eth4, my browser didn't see any devices.  So I tried plugging UniFi into my laptop and the browser saw the UniFi.  I wasn't sure if my EdgeRouger was setup correctly.  When I tried to connect to the router, I wouldn't.  On eth1 EdgeRouter would assign an IP to me, but I couldn't get to the GUI.  On ports eth2, eth3, eth4 I didn't even get an IP.  So I did a factory reset.  Then I thought I could just upload the file edgeos_ubnt_20170221.tar.gz to my router, hoping this was the same as the config in the manual, but I didn't get any IPs assigned to any ports.  So I factory reset again.  Is there a backup file that matches the manual?

**Comment by mjp66** [comment]
I have not been keeping the backup file or the show config data file up to date. I recently added a statement to this effect, to the guide. Reasons are: 1. Way too much regression work. 2. People won't learn, if they simply load and don't participate / follow along / tinker. 3. I'm trying to add new sections and content.

Even though the backup file is about 10 months old, you can still load it and use it to test your hardware. It matches the document which was committed at the same date and is perfectly functional.

You should be able to go to the system page and load that backup file, then reboot the ER-X. Ensure your PC is configured for DHCP, connect it to eth3, wait about 5-10 mins for the ER-X to boot and then login.

-Mike
