### ISSUE TITLE
Firewall rule 3 destination group?

### ISSUE THREAD

**Issue by Scott216** [mjp66/Ubiquiti#22]
In sect 53 firewall rule 3, there's an empty destination group entry.  Is the destination group entry supposed to be empty in rule 3?  In the other rules where destination group is empty, there's no text at all in the backup styled config.  But this one has destination group, but with no setting.  I wanted to make sure this wasn't a typo.

**Comment by mjp66** [comment]
At first glance, it looks like you have found either a document error or something left over from my earlier experimenting. It appears that the text:
`destination {
group {
}
}`
is not in the published backup file. I'll remove this text from the guide upon my next guide update. Good catch.

-Mike

**Comment by mjp66** [comment]
Fixed
