### ISSUE TITLE
Additional Network Language Clarificaiton

### ISSUE THREAD

**Issue by ucdscott** [mjp66/Ubiquiti#24]
Section 18 on page 26 reads, "This allows us to provide for an additional Network." but should state, "Un-bundling the interface from switch0 enables a separate **_physical_** network."

i.e. an additional network can be achieved by adding a logical VLAN but you are choosing to implement an additional network on the physical switch port.

**Comment by mjp66** [comment]
Thanks for the update. Added to doc.
