### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by AboveMyPaygrade** [mjp66/Ubiquiti#26]
This guide has been incredibly helpful to me, despite the fact that I have the UniFi line of products (as opposed to the EdgeRouter line discussed within).  I'd love to see it maintained, at least, if not grow to cover some of Ubiquiti's other lines (even if not, this has been quite instructive).  

Are you taking donations?

**Comment by mjp66** [comment]
Thanks for the compliment. I wrote this guide because I REALLY like this equipment. I don't have any UniFi equipment, so will probably not expand this document to encompass any new equipment. Thanks for the donation offer, but no, I'm not. I'm glad this guide has helped you.
