### ISSUE TITLE
Download speed cut in half with EdgeRouter X

### ISSUE THREAD

**Issue by Scott216** [mjp66/Ubiquiti#28]
When I setup my EdgeRouter X, my download speed went from 113 Mbps to 53Mbps.  This is on a wired connection.

**Comment by rmoorewrs** [comment]
I'd recommend visiting the Ubiquiti community site for EdgeMax.. there could be a number of issues, and the community there is very helpful. [Ubiquiti EdgeMax Community Forum](https://community.ubnt.com/edgemax).

Properly configured, you should be able to get *much* better performance than that. Some of the issues that can cause slow performance are:

QoS, DPI, software bridging of interfaces (vs using the integral switch), HW NAT acceleration, etc

FYI, I have gigabit internet service and at first I only got about 300mbps with the ER-X, but after turning off DPI and QoS, and turning on HW NAT acceleration, I'm getting 800-900mbps.

Good luck!

**Comment by Scott216** [comment]
Thanks.  I'll check out the forum.  I have my edgerouter setup as instructed by the guide in this repo.

**Comment by MikeWills** [comment]
The author has stated that they are not a network engineer. This config works for me, but I have 8mbps. I assume QoS is less important at higher speeds.

**Comment by jeclark15** [comment]
I've had no issues getting a full 100M through the ERX with DPI and QoS enabled as specified by this guide. Do you have Config Tree -> System -> Offload -> hwnat enabled?

**Comment by mjp66** [comment]
@Scott216
Please re-read the following guide sections and follow links.
ER-X's are capable of about 800Mpbs total.

32. EdgeRouter Enable HW NAT Assist
Use section's link to Verify hwnat is enabled.

33. EdgeRouter ER-X Speed
Six links provided.

34. EdgeRouter Enable Traffic Analysis
Guide says: "This step will enable the EdgeRouter to perform Deep Packet Inspection (DPI) / Traffic Analysis. If you have any speed issues with your ER-X, then this may need to stay off."
Turn Off.

59. SmartQueue Setup
Guide says: "Enabling QoS may disable the hardware acceleration that was enabled in section 32 - EdgeRouter Enable HW NAT Assist."
Turn Off.

Also check that eth0 is not sensing / locked at 100Mbps. Eth0 should be green at top of dashboard screen.

Also try a new / different Ethernet cable between Cable Modem and ER-X eth0, even if you think the existing cable is fine.

To test for an ERX duplex mismatch, you can temporarily add a new gigabit hw switch between the cable modem and erx's eth0 as a test. Check for green. Ensure that only those two items are connected to this temporary switch.

-Mike

**Comment by Scott216** [comment]
Thanks Mike.  I'll let you know how it turns out.

**Comment by mjp66** [comment]
Reference https://community.ubnt.com/t5/EdgeRouter/EdgeRouter-X-only-getting-50-75-throughput/td-p/1870333
