### ISSUE TITLE
Link request

### ISSUE THREAD

**Issue by AboveMyPaygrade** [mjp66/Ubiquiti#3]
Absolutely excellent guide.  If it's no trouble, I suggest adding a link somewhere in the front pointing to this repo.  If anything, you deserve props, and people should be able to easily get back to the source for updates, as I'm certain this guide is going to start popping up all over the place.

Your guide was plugged on the Security Now podcast, episode 641, hosted by Steve Gibson (the reviews were glowing):

https://www.grc.com/sn/sn-641.htm

**Comment by mjp66** [comment]
Thanks for the compliment. Heard the SN reference. Added link near title.
