### ISSUE TITLE
Add Google Fiber Config

### ISSUE THREAD

**Issue by B3nd3r15** [mjp66/Ubiquiti#31]
Great job on the writeup. I'm currently using your config for my setup and am loving it. One thing I wish i knew where/how to do would be to add google fiber config to eth0. Below is a snippet of steve jenkins setup with google fiber, But I like your setup better just want to get rid of my fiber box. https://github.com/stevejenkins/UBNT-EdgeRouter-Example-Configs/blob/master/Google-Fiber/config.boot.erx

    ethernet eth0 {
        description "Google Fiber Jack"
        duplex auto
        speed auto
        vif 2 {
            address dhcp
            description "Google Fiber WAN"
            dhcpv6-pd {
                pd 0 {
                    interface switch0 {
                        host-address ::1
                        prefix-id :0
                        service slaac
                    }
                    interface switch0.102 {
                        host-address ::1
                        prefix-id :1
                        service slaac
                    }
                    prefix-length /56
                }
                rapid-commit enable
            }
            egress-qos "0:3 1:3 2:3 3:3 4:3 5:3 6:3 7:3"
            firewall {
                in {
                    ipv6-name WANv6_IN
                    name WAN_IN
                }
                local {
                    ipv6-name WANv6_LOCAL
                    name WAN_LOCAL
                }
                out {
                    ipv6-name WANv6_OUT
                    name WAN_OUT
                }
            }
        }
    }

Thank you

**Comment by mjp66** [comment]
Added a quick reference to section 13 - Network Naming.
