### ISSUE TITLE
Answer to your question

### ISSUE THREAD

**Issue by mvl64** [mjp66/Ubiquiti#32]
Hi Mike,
I've reviewed the closed "issues" reported to your excellent guide and don't believe it is already.
So, let me try to give something back :-)

In page 38, you ask "QUESTION: Is there a way to combine the Wired IOT Network and the WiFi IOT Network?"

The hardware switch chip will only support one switch group - but you could theoretically bridge two other ports. This would result in slower throughputs as the bridging is handled in software instead of in hardware. Another downside would be that you need another access point next to the one already in use (which is part of switch0).
As an alternative, you could add a managed switch and assign a VLAN for the combined_IOT networks. In the managed switch, you could combine the wired and wireless clients into one network segment (this would require you to move the access point to the managed switch too, so you can assign the various VLANs to the access point there)

So, in my view it would be possible but at some cost.

My question in return would be: what is the reason you would want to combine these ?
For my IoT networks the security setup is very restrictive - I only want the IoT devices to access the internet and not have communications between each other.

**Comment by mjp66** [comment]
A number of people have asked me about / wanted a combined the Wired and WiFi Iot networks.
See section 76 - Coalescing the Wired Iot and Wifi Iot Networks.
