### ISSUE TITLE
Streaming media from HomeNet to (Wifi)IOTNet

### ISSUE THREAD

**Issue by mpegyna** [mjp66/Ubiquiti#33]
Hello again,
thanks to your guide I've already set up home networks at two places. So far so good.
I was using BubbleUPnP for DLNA/Chromecast to stream my media (cloud and noncloud)
from my Android phone to Samsung Smart TV, since Google deliberately disabled Miracast
in the middle of Marshmallow version od Android. And also with DLNA I could have screen
off on my mobile.

But now with some updates to Android, BubbleUPnP for DLNA/Chromecast and my home
network reworked, it sadly doesn't work. I have all Smart TVs on WifiIOTNet because they
are from 2012/2013 and don't trust them. But it doesn't work even when I connect my
Android phone to WifiIOTNet. So I'm wondering if it's a home network configuration
problem, or Android / BubbleUPnP for DLNA/Chromecast problem.

PS I don't want to buy Chromecast or some other dongle only for casting media to my old
Smart TVs. BTW Chromecast is slightly better and very overpriced Miracast anyways (All my
TVs support Miracast).

**Comment by mjp66** [comment]
Sorry, but I don't have any of this equipment, and I don't trust setting up UPnP. You will just need to research, experiment, and test.
