### ISSUE TITLE
Wireguard?

### ISSUE THREAD

**Issue by patrickdo** [mjp66/Ubiquiti#37]
Hi, thanks for the great guide. I've followed almost all of it, except for not having a Wired Separate network. I have installed Wireguard (33.x) on my ERX and my Android phone and through WG, I am able to view IP cameras that are on my Home net (3.x), but not able to view those on the WiFi IoT net (7.x). I can view all cameras when I'm on the Home net (3.x). Is this expected behavior?

I have tried adding 33.x to the Home user group and I've tried copying the HOME_LOCAL firewall rules to make a WG_LOCAL (changing interface to wg0), but haven't been successful. Do you know what I can do to view WIFI IOT devices from Wireguard?

Thanks!

**Comment by edwardsmarkf** [comment]
have you seen this?

https://store.ui.com/collections/routing-switching/products/edgerouter-10x?utm_source=Ubiquiti+Newsletter+Subscribers&utm_campaign=4f0b118314-EMAIL_CAMPAIGN_2019_04_25_01_42&utm_medium=email&utm_term=0_1c1b02cb37-4f0b118314-238331045




Thank you,

Mark Edwards

**Comment by mjp66** [comment]
@patrickdo If you can already interact with the IOT cameras directly from the HomeNet, then I wouldn't know how to help. Sorry. I'll leave this up for a while, in case somebody else can help you. You might need to join/ask on the Ubiquiti forums.

@edwardsmarkf I first heard about the 10X via this post, which was a couple of days ago.
[https://community.ubnt.com/t5/EdgeRouter/Anyone-want-to-share-their-experience-with-ER-10X/m-p/2765723/highlight/true#M250254](https://community.ubnt.com/t5/EdgeRouter/Anyone-want-to-share-their-experience-with-ER-10X/m-p/2765723/highlight/true#M250254)

-Mike

**Comment by patrickdo** [comment]
Just saw the notification that this is closed. I was able to fix the problem in the end. I had to add the WG's 33.0/24 subnet to pre-authorization access in the Unifi AP controller settings.

**Comment by mjp66** [comment]
Glad you got it working.

**Comment by edwardsmarkf** [comment]
mike - when you have an official "book signing" for your gist, could i get
a selfie pic with you??  😃

Thank you,

Mark Edwards
