### ISSUE TITLE
not an issue, rather, a question about the new edgerouter-10x

### ISSUE THREAD

**Issue by edwardsmarkf** [mjp66/Ubiquiti#38]
hi - this new edgeRouter-10X appears to eliminates the need to have the auxiliary switch:

https://store.ui.com/collections/routing-switching/products/edgerouter-10x

have you tried it?   is it worth updating the instructions over?

**Comment by mjp66** [comment]
@edwardsmarkf  Hardware looks sweet.

Maybe I'll get a chance to buy one in about a year. I can put a shout-out that the 10X model exists, in the next release of the guide.

Timing of buying one now would depend (for me) if this unit needed the V2.0.X series of firmware. Ubiquiti had quite a firestorm on their hands with the following releases, as it pertains to the ER-X model. There are over 400 replies to the 2.0.1 thread. They first had to retract the release of 2.0.0 for the ER-X. Even their 2.0.1 fix had to be retracted for the ER-X. The 2.X series uses a new code base, and was not ready / stable for the ER-X platform. I perceive that the 2.X code was reasonably stable for other platforms. These releases likely caused a bunch of (semi?) bricked ER-X units.

[https://community.ubnt.com/t5/EdgeRouter/EdgeMAX-EdgeRouter-software-version-v2-0-0-has-been-released/m-p/2622433/highlight/true#M235165](https://community.ubnt.com/t5/EdgeRouter/EdgeMAX-EdgeRouter-software-version-v2-0-0-has-been-released/m-p/2622433/highlight/true#M235165)

[https://community.ubnt.com/t5/EdgeRouter/EdgeMAX-EdgeRouter-software-version-v2-0-1-has-been-released/td-p/2730981](https://community.ubnt.com/t5/EdgeRouter/EdgeMAX-EdgeRouter-software-version-v2-0-1-has-been-released/td-p/2730981)

-Mike
