### ISSUE TITLE
Detailed differences between 2019_02_04 and 2019_05_18

### ISSUE THREAD

**Issue by mjp66** [mjp66/Ubiquiti#39]
2019_05_18 was a pretty big change. I re-configured an ER-X from scratch, updating the guide and screen-shots as I went. Therefore, I've added a new reference backup/config file.

NewSections: 4, 32, 38, 39, 40, 58, 75, 78, 82, 83, 84, 85, 86, 87, 88, 90.
UpdatedSections: 52, 54, 60.
NotableChanges: Pages75-78, Pages111-114, 'RFC-1918'.

I've included a document difference, for this release, created with my favorite program "Beyond Compare". I am not affiliated with them. Their exported difference reports are natively generated as html files, but github will not accept html files. I had to print-as a PDF file, and my PC only supports a limited number of sizes. So the attached file is not in an optimal (i.e. wide) format. Hopefully this information is still useful to somebody.

[Diffs_2019_02_04 vs 2019_05_18.pdf](https://github.com/mjp66/Ubiquiti/files/3194487/Diffs_2019_02_04.vs.2019_05_18.pdf)

-Mike

**Comment by patch01** [comment]
Hi Mike, your guide has been a fantastic help to me. I followed it to the letter and had no trouble whatsoever with the config. So thank you!

Just one question, do you have any plans to include dual stack IPv6? I would try this myself, but I'm not 100% confident with ensuring that the Firewall Rules get adapted correctly.

Thanks again,
Patch

**Comment by mjp66** [comment]
Hi @patch01,
 
Thanks. I don't have any plans for iPv6, as I don't have that service available.
You will just need to research iPv6 yourself.

If you can afford it, purchase a second ER-X. Then you can keep one unit as production, while performing research / configuration / tests on a second unit, swapping routers as needed.

-Mike

**Comment by patch01** [comment]
Thanks Mike. I do have a dev unit that I purchased before implementing your solution. So as you suggest, I'll experiment on that one.
Regards,
Patch
