### ISSUE TITLE
port forwarding?

### ISSUE THREAD

**Issue by edwardsmarkf** [mjp66/Ubiquiti#40]
do you know anybody who has port forwarding or port redirect experience on this router?  i can't seem to get it working.

**Comment by gilbreen** [comment]
I have it set up and working following the steps from this video.  The change did not work when I used the "Enable auto firewall" option, so I followed the instructions in the video on how to manually add the firewall policy.

Good luck!

https://www.youtube.com/watch?v=t8Hy_0v8JBQ

**Comment by edwardsmarkf** [comment]
thank you - i did everything on the video, but still no success.  i even
tried DELETING all the rules!

i am thinking my problem must be at a more *basic* level.     for fun, i
also configured a rasberry-pi to show me a webpage.  it works fine when i
go to http://192.168.100.77:8080  but **NOT**  when i go to
http://192.168.100.1:8080 even though i have port 8080 traffic directed to
192.168.100.77  -- and i am also using the parent gateway as well.   all of
this stuff works fine on the parent, but not using the edge-max router.

this issue sure is challenging.


Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
dang...   its actually been working all along...  how embarrassing is that?

Thank you,

Mark Edwards
