### ISSUE TITLE
PDF Typo Section 86-Page 138

### ISSUE THREAD

**Issue by Zaf9670** [mjp66/Ubiquiti#44]
It currently shows "This example will involve allowing an SSDP rely from" but I believe you mean relay.

Very useful guide! I am going through it to assist me setting up our home network. I have two roommates and one works from home so I'm currently setting him up with his own "work" port and the rest of the house going through the various switches I have located in the house.

**Comment by mjp66** [comment]
Will update to "reply" upon next guide release. Thanks.
