### ISSUE TITLE
Why not put eth 1-4 into switch0

### ISSUE THREAD

**Issue by hypervalhalla** [mjp66/Ubiquiti#45]
Hi there,

First of all I really like you guide. It was very usefull too me in the past to get understanding about some networking principles.
So now I'm a little further with experimenting and wondering the following thing:
Why do you choose to split eth 1 and 2 in seperate physical lan's and why not choose to VLAN them too? Is there some benefit or do I miss some technical background here?

Thanks!

**Comment by miquelfire** [comment]
Eth 1 might be because it's meant for a secure computer that won't be infected by other systems. That's all that I can see for that reason.

Eth 2, I added it to the switch in the VLAN for the IOT network for the one wired device that needs to be on the IOT network.

**Comment by mjp66** [comment]
Excellent question.

I implemented VLANS late in writing the guide.  It was too much work to go back and re-write the entire document and re-take all those screenshots to implement VLANS from the beginning. When I did implement them, I was only concentrating on the Home Network. Should be able to implement eth1 and/or eth2 as VLANS.  I’ll see about adding them to the document and config file for a future release.

**Comment by hypervalhalla** [comment]
Thank you guys for the clarification really helpful. 

Offtopic, in case you are creating a future release: all the images in the PDF are quite blurry. I have a copy from 2017 where the images are sharp. So I guess an exporting issue.

Thanks again!
