### ISSUE TITLE
Thank you very much for all your hard work

### ISSUE THREAD

**Issue by alam** [mjp66/Ubiquiti#49]
Hello @mjp66 👋🏽 ,

I just want to take this chance to thank you for this amazing resource. Like you, I was very worried about the security issues with consumer networking equipment and switched over to a similar setup circa 2018. I got everything up and running back then, but I always had this nagging feeling at the back of my mind wondering if I had done things correctly or understood everything well. Your guide has been indispensable allaying many of my worries, so again, thank you very much!

- Alam

P.S. Sorry I had to use a Github Issue, I couldn't find any other way to contact you.

**Comment by mjp66** [comment]
Thanks, and you are welcome.
