### ISSUE TITLE
New controller versions - different config options

### ISSUE THREAD

**Issue by rmarmorstein** [mjp66/Ubiquiti#50]
Hello,

I love the guide! It is very well put together, and I appreciate the time you've put into this.

I've run into an issue, it appears that you are using controller version 5.4.11, which uses the classic settings.

The latest controller version is 6.0.43. There is a whole new settings page (Beta). It allows you to swap back to the Classic Settings, but it doesn't have all of the same options.

Perhaps I did something wrong? Otherwise, it looks like this may be something to add to the to update list.

Thanks!

**Comment by mjp66** [comment]
There are about a hundred posts on the Ubiquiti community site telling people to downgrade from using the 6.X controller, for various reasons.  

There are even **more** postings about downgrading Access Point firmware, (typically to 4.3.20 at this time), because of Wi-Fi instability in Ubiquiti’s newer AP firmware(s).

Good luck, hope you saved an earlier-version controller backup file.
-Mike

**Comment by edwardsmarkf** [comment]
is this recommended downgrading something Ubiquiti is concerned about?
 usually whenever i hear about a recommended downgrade, it seems like there
are serious quality control issues.

Thank you,

Mark Edwards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mjp66** [comment]
@edwardsmarkf You decide if Ubiquiti is concerned about quality. I picked the following release-link, mostly at random. Read down through the postings, or at least the first couple of pages.

https://community.ui.com/releases/UniFi-Network-Controller-6-0-23/6ee72622-e3ca-4ebe-9e82-97fe7cca2094

If your system is working, I wouldn’t update / upgrade it. There seen to be serious quality issues, not necessarily security issues, in the last year or so with Ubiquiti releases.  See minor updates (I.e. version notes) made to the guide (today) January 17, 2021.

-Mike

**Comment by edwardsmarkf** [comment]
Mike - i dont pretend to be smart.   that is why i rely HEAVILY on many
different forums, and fools like you* who answer my idiotic questions.

let me see what kind of reply i get back here:
https://community.ui.com/questions/EdgeRouter-upgrade-question/18cbd0d6-fc6b-4940-886d-6e72b03c953d

*kidding - i don't consider you a fool - and i am very grateful to you for
your work in making the edgeRouter simpler.  it's beyond me why it takes
somebody like you outside the company to simplify the damn thing.

Thank you,

Mark Edwards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rmarmorstein** [comment]
@mjp66 Thank you for the super helpful reply....

May want to note, your guide tells people:

> Under the SOFTWARE section, download the NEWEST “Unifi Controller for Windows” software (Unifi-installer.exe).

Note: NEWEST - all caps too. Perhaps something in there about not using the latest version would be helpful? I don't know about others, but I don't typically go searching forums for problems I don't know exist until after I find out about them. 

I was able to figure out the rest of my setup without your guide. I am very thankful for the work you've done, but perhaps some edits to prevent future users from suffering the same frustration as I would be helpful.
