### ISSUE TITLE
94. Simple Service Discovery Protocol (SSDP) / igmp-proxy

### ISSUE THREAD

**Issue by Tobalp** [mjp66/Ubiquiti#51]
Greeting,
First of all thank you so much for your effort and making this guide, it helped me a lot, I'm only having trouble getting my roku stream stick and LG TV to cast on my trusted network, and if it's possible on guest network too, so can you please post your settings for this section of the guide in your next update, thanks in advance.

**Comment by mjp66** [comment]
Sorry, but what I have is already in the guide.
