### ISSUE TITLE
None of the ports work except for the switch ports 3,4

### ISSUE THREAD

**Issue by energycl01** [mjp66/Ubiquiti#52]
Hello,

I followed the manual and tried configuring the EdgeRouter X twice after a system reset, but both times only ports 3 and 4 will connect to the internet and I can't get into the console other than ports 3, 4.

Anyone know what might be causing the issue

Thanks

**Comment by mjp66** [comment]
Sorry, never heard of this. You might try a different instance of hardware, or try posting your config to the community.
