### ISSUE TITLE
Ubiq EdgeRouter support might be deteriorating.

### ISSUE THREAD

**Issue by edwardsmarkf** [mjp66/Ubiquiti#53]
hello - 

according to several posts:

https://community.ui.com/questions/EdgeRouter-upgrade-question/6eff11be-b781-4ced-8a00-6b8a75a34464
https://www.reddit.com/r/Ubiquiti/comments/lxx2ti/ubiquiti_rant/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Ubiquiti is no longer a great company to purchase equipment from.  Apparently there was some sort of internal strife there and many of the people left the company.

And the firmware version 2.x is not being well received by the community.

so, i am searching for a new "favorite brand".  MicroTik seems to be very highly regarded.

any other opinions on this?  i only went with EdgeRouter because of Ubiquiti's reputation, or should i say their former reputation.  or perhaps the concerns are overblown and the EdgeRouter is still a solid option?

**Comment by mattkime** [comment]
What problems are you having? Or are you purchasing based on online forum grumbling?

I don't think the accusations regarding stability are wrong per se, but it seems quite manageable for the intended audience of this document.

**Comment by edwardsmarkf** [comment]
i am not purchasing based upon online forum grumbling.  but i sure will
look a bit more carefully next time i make a purchase.   i am experiencing
no problems, other than concern that Ubiquiti quality may have begun to
"slip".

reply from reddit:
https://www.reddit.com/user/edwardsmarkf/comments/m4yt6c/auth0com_and_okta/grv5yer/

but again, previously Ubiquiti was my go-to source for any networking gear,
and for several years now i have not bothered even researching any other
solutions, i went straight to Ubiquiti and never looked back.

but hearing so many forum complaints about buggy firmware upgrades has me
concerned.


Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
sorry WRONG reddit link - apologies.

Thank you,

Mark Edwards
