### ISSUE TITLE
Up to Date EdgeRouter X config file for 2021

### ISSUE THREAD

**Issue by hf444** [mjp66/Ubiquiti#56]
Hi, 
A question, not an issue.

Thank you for this informative project / document. 
 Such a labor of love and devotion.

Since there have been numerous changes to the earlier document, 
do you have a newer / up to date edgeRouter X config file that would accompany the latest release  of 04-21-2021 ?

Thank you .
hf444

**Comment by mjp66** [comment]
Hi,

Thanks.

No, I don’t have an updated file, and am unlikely to produce another “reference” config file. One reason is that it is very difficult for me to keep a file synced with my guide. Many of the sections are optional, other sections have choices the reader needs to make on their own. One configuration does not match all readers.

Another reason is that I believe the best way for someone to learn is by actually doing. I think the real benefit of my guide is walking through it and understanding what you are doing. Then you will be able to control / configure your network, however you want.

-Mike

**Comment by hf444** [comment]
Hi Mike,
Thank you for your response. 
Your explanation makes sense.

This guide of yours is so complete, WELL WRITTEN, and helpful for the beginners (and I would think for many knowledgable folks)...
 it seems like it would" stand the test of time" going forward.
BUT ( of course isn't there always a ...)

1.  Somewhere (possibly on the Ubiquiti community) I thought I had read that you do not recommend moving the ER X onto the 2.0.x ++ firmware ?
Other than " it works on the 10.11 so why change it " type of answer, 
should an ER X user try to follow the factory and try to keep the ER X up to date?
And what type of issues rear their ugly head if one did try to keep the ER X up to date?

Especially when following this guide?

2.  Since you are so knowledgeable, a GOOD Documenter,  and a GOOD "teacher",
     Have you have moved on to a  BETTER SOLUTION / SETUP  ?
If so, is it still Ubiquiti, and what might that be?
And are you considering explaining that for the rest of us?

Again, THANK YOU for your valuable assistance to the Ubiquiti community.

hf444

**Comment by miquelfire** [comment]
I'm sure there are reasons to not switch to 2.0.x yet for some people. Early days there was a bug that caused it to just drop all packets after a while making it appear to lock up, but that appears to have been fixed (and if it hasn't, the current fix at least allows the router to recover so you don't need to unplug the damn thing once every few days, or once a week)

**Comment by mjp66** [comment]
IF I moved to a new firewall, it would probably be pfSense on protectli hardware.  Expensive, estimate about $300US.

https://forums.grc.com/threads/my-favorite-utilities-gadgets-services.163/post-1354

https://forums.grc.com/threads/my-favorite-utilities-gadgets-services.163/post-1355
