### ISSUE TITLE
Troubleshooting ER-X filters?

### ISSUE THREAD

**Issue by kd5byb** [mjp66/Ubiquiti#6]
Have had my ER-X for several weeks now set up per your excellent document and it's working great!  Have forwarded several folks towards your write-up and the ER-X.

Quick question - is there a troubleshooting procedure document you can recommend for troubleshooting ER-X filters?  

I've got an NTP server on my IOT_wired and while the clients on Home_Net can see and sync to it without issue...when I issue the "remote" ntpq -p 192.168.4.50 (where 4.50 is the NTP server) I get no response like its being filtered.  Opening up the NTP UDP port (as well as opening it up to both UDP and TCP) didn't help.  I'm probably doing something brain-dead...but have no idea how to troubleshoot where the cute little packets are getting lost.  :)

thanks much,
ben

**Comment by mjp66** [comment]
Sorry, but I'm not a network engineer.

I suggest you either search the Ubiquity EdgeMax forum at
https://community.ubnt.com/t5/EdgeMAX/bd-p/EdgeMAX
or create an account and ask them.  If you ask the forum, they will probably want you to post your (slightly redacted) ER-X configuration file and/or network map.

If you post, you can reference this github repository as source or
https://community.ubnt.com/t5/EdgeMAX/New-ERX-AC-AP-LR-setup-guide-for-beginners/td-p/1906477
as source or neither.

For example there is a new post about ntp at
https://community.ubnt.com/t5/EdgeMAX/Need-help-fix-ntp-error/td-p/2203423.

Help this helps,
-Mike
