### ISSUE TITLE
RDP Via Site-to-Site VPN

### ISSUE THREAD

**Issue by myatix** [mjp66/Ubiquiti#60]
Hi,

I have been trying to setup a Site-to-Site VPN with my Edge Router 4 and Azure but even though the VPN is successfully connected I just cannot RDP to any machines in Azure???

I used the below guide as a reference and the VPN tunnel is showing as connected successfully.
https://help.ui.com/hc/en-us/articles/115012305347-EdgeRouter-Route-Based-Site-to-Site-VPN-to-Azure-VTI-over-IKEv2-IPsec-

Do I need to add a firewall rule to allow traffic from Home_Out to VTI0 (Virtual Tunnel Interface 0)?

I tried setting up an Allow Rule in Home_Out to source VTI0 but this didn't seem to resolve the issue. Any ideas???

Great guide by the way I have been using it for the last 2 years!

**Comment by mjp66** [comment]
Sorry, I know nothing about configuring VPNs on ER-X. You might try the ui.com community.

-Mike
