### ISSUE TITLE
Static network device not listed by Edgerouter-X

### ISSUE THREAD

**Issue by stevesr0** [mjp66/Ubiquiti#61]
Hi,

Thanks for guide.

I have a multifunction printer attached via ethernet to an Edgerouter-X. Works fine both for printing and scanning.  I had set up a static LAN IP address for this device before buying the Edgerouter.  Today, I looked for the device, but it isn't listed on the static mapping, nor the dynamic mapping.

I see that I could set it up as a "new" static ip address, but I don't want to end up with some problem because of making a duplicate.

Do you happen to know of a way of getting the Edgerouter to recognize the existence of this static ip address?

Thanks.

Steve Rinsler

**Comment by scottj97** [comment]
The static IP should be okay as long as it's outside the DHCP range configured in the ER-X. Another option is to switch the device to use DHCP and add a static mapping in the ER-X interface. Either way the IP will be consistent over time.

**Comment by stevesr0** [comment]
Thanks, Scott.

If I change it to use dhcp, presumably on a computer rather than via the router, then the router should detect it?

And then edit it on the router from a dhcp entry to a "reserved"/static mapping one.

I wonder if that is any different from just deleting it from a computer and then creating it on the router?

My pickiness is due to the problems I had getting the scanner attached to the router recognized by my computer.  I don't want to have to configure things again.

Steve Rinsler






On Monday, February 28, 2022, 05:17:12 PM EST, Scott Johnson ***@***.***> wrote: 







The static IP should be okay as long as it's outside the DHCP range configured in the ER-X. Another option is to switch the device to use DHCP and add a static mapping in the ER-X interface. Either way the IP will be consistent over time.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by scottj97** [comment]
By "change it to use DHCP", yes I meant you go to the printer's setup page, however that works, and reconfigure its network settings to dynamic instead of static.

It's not a matter of the router "detecting" it...it should work just fine with a static IP address. The danger is that the ER-X might assign that same IP to a different device, if the chosen static IP is within the range of the DHCP addresses that the ER-X is configured to assign. In that case you will have trouble.

I'm not sure what you mean by "deleting it from a computer and then creating it on the router"...that sounds like the same thing I'm talking about (switch it from static to DHCP, then create a reservation on the ER-X so it always gets a predictable IP address).

Are things working now? If so, and if the printer's static IP is outside the DHCP range, then I'd say no changes are needed.

**Comment by scottj97** [comment]
In any case, this is not an issue with this setup guide, so this is a question better asked in Ubiquiti's forums.

**Comment by stevesr0** [comment]
Hi Scott,

I appreciate your assistance.  I have successfully made the change in the router for the device.

I do think this is something that could be covered in the nice manual that you folks have produced.

I didn't see any other place where getting the router to manage static ("reserved") ip addresses was explained.

Steve Rinsler

On Monday, February 28, 2022, 07:12:27 PM EST, Scott Johnson ***@***.***> wrote: 







In any case, this is not an issue with this setup guide, so this is a question better asked in Ubiquiti's forums.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GeoffWy** [comment]
If you are allocating the static address by DHCP this is covered in Section 86 of the guide.

If you are fixing the address at the printer, then the router plays no part in managing the address so that is why that option is not covered in the guide. You may choose for your own convenience to record the address the printer is set to as a dhcp static address, but the router is playing no part in the allocation or management of that address. The printer will work just as well if you don't set it as a static IP in the router and its entirely up to you that you set a printer address that does not clash with anything else in your network.

**Comment by stevesr0** [comment]
Thanks GeoffWy,
I want to be able to see all the devices attached to the router physically or via the wap.  Everything was showing up except the printer/scanner.  Apparently because it had a “static” IP address that wasn’t set by the router. 
So, I followed the instructions in the guide and from Scott ( thanks) and converted the device to a dhcp address and then in the router web page to a “reserved” (static mapping) address.
Then it showed up…and everything still connects to it.
(The only thing I noted, which I think is unimportant, is that the device has dns servers set which are different from those of the router.  Since it is “behind” the router, I don’t know that it matters, but I will lookup whether this should just be set to the router address or to the addresses of the dns servers the router is set to.)
Steve Rinsler

Sent from Yahoo Mail for iPad


On Tuesday, March 1, 2022, 06:30, GeoffWy ***@***.***> wrote:




If you are allocating the static address by DHCP this is covered in Section 86 of the guide.

If you are fixing the address at the printer, then the router plays no part in managing the address so that is why that option is not covered in the guide. You may choose for your own convenience to record the address the printer is set to as a dhcp static address, but the router is playing no part in the allocation or management of that address. The printer will work just as well if you don't set it as a static IP in the router and its entirely up to you that you set a printer address that does not clash with anything else in your network.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GeoffWy** [comment]
The DHCP solution may meet your needs, but it is not actually telling you that a device is connected, it is telling you that a particular address has been leased to your device for a period of time (probably 24 hours). After the lease has been issued you could disconnect your printer and it would still show in the DHCP leases.
I am not sure what you mean by wap in this context. I assume what you mean is that you want to see everything that is connected to your local area network. You can do that by opening a command window on the edgerouter and type in "show arp" and you will get a list of everything on your lan. I do not know of a way of accessing the same information through the user interface.

**Comment by stevesr0** [comment]
Hi GeoffWy,

Sorry for confusion.

1. I have the multifunction device NOW set by "static mapping" in the Edgerouter web interface.  I assume that that the device will have that IP address unless and until I change it.

2. The Edgerouter web interfaces seems to be displaying all devices that are attached to it.

That is what I wanted to accomplish.

If I am missing something, I would greatly appreciate clarification/correction.

Thanks again for your helpful comments and the wonderful guide to the Edgerouter-X.

(In the course of working on this, I realized that I have to review my DNS server setup, but that is for another thread if I can't figure it out and I think it is within the purview of the guide.)

If all seems OK to you after reading this note, I will mark this issue as solved and close it.

Steve Rinsler

P.S. wap=wireless access point.  That is one of the devices connected to my Edgerouter.  The wifi devices linked thru that also show up in the Edgerouter listing, which is nice.

On Tuesday, March 1, 2022, 09:45:19 AM EST, GeoffWy ***@***.***> wrote: 




The DHCP solution may meet your needs, but it is not actually telling you that a device is connected, it is telling you that a particular address has been leased to your device for a period of time (probably 24 hours). After the lease has been issued you could disconnect your printer and it would still show in the DHCP leases.
I am not sure what you mean by wap in this context. I assume what you mean is that you want to see everything that is connected to your local area network. You can do that by opening a command window on the edgerouter and type in "show arp" and you will get a list of everything on your lan. I do not know of a way of accessing the same information through the user interface.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mjp66** [comment]
I’ll add some explanation of (external) static IP mapping, in the next release of my guide.
