### ISSUE TITLE
any unifi uap-ac-pro firmware above 4.0.80.10875 does not work with vlan tagged networks

### ISSUE THREAD

**Issue by ianhundere** [mjp66/Ubiquiti#63]
so i'm curious if you've had success updating to anything higher than  `4.0.80.10875`, and if so, how?

everytime i try to update, i lose internet connectivity.

**Comment by mjp66** [comment]
See Section 67 -> Notes 4 & 5, of guide released on 6/3/2022.
I don't have a Pro. I just pushed the button in UniFi to update firmware.

**Comment by mjp66** [comment]
Just saw this:
https://community.ui.com/questions/UAP-AC-PRO-hangs-during-firmware-update/58b53b4f-5509-4140-8f1f-dd6702e5bc77

**Comment by ianhundere** [comment]
cheers, i'll check that out. maybe i need to update manually via ssh?

thanks again
