### ISSUE TITLE
Any update currently this date for Firmware v2.0.9-hotfix.2 (ER-X)

### ISSUE THREAD

**Issue by chroots** [mjp66/Ubiquiti#65]
I still using your configuration setting, wanted to know any update for Firmware v2.0.9-hotfix.2 firmware with all setting contain like i did use your edgeos_ubnt_20190518.tar.gz uploaded via GUI on EdgeRouter X v1.10.11.

**Comment by mjp66** [comment]
I believe the following is what you are asking:
- In guide around page 19: "2022 Note: I am now on 2.0.9.hotfix.2, and do not have any problems."
- No configuration changes are needed to switch from 1.10.11 to 2.0.9.hf2.
- Make a new backup (of your current ER-X settings), then just update the firmware, which will reboot the ER-X.
