### ISSUE TITLE
CLI syntax changes pages 76-77 for DNS service config

### ISSUE THREAD

**Issue by rotor-head** [mjp66/Ubiquiti#68]
Written:

`show dns forwarding nameservers`

In 2.0.9.xxx the syntax is:

`show service dns forwarding name-servers`

A side note; what a monumental undertaking to create this fantastic document. I've been using Ubiquiti gear for a number of years and just now discovered your work. Thank you.

**Comment by mjp66** [comment]
Hi,

Sorry for the delay.
The original command seems very much alive to me.
I had to strip out the dashed lines in the below response.

@ER-XRouter:~$ show version
Version:      v2.0.9-hotfix.7
Build ID:     5622731
Build on:     06/15/23 08:57
Copyright:    2012-2020 Ubiquiti Networks, Inc.
HW model:     EdgeRouter X 5-Port

ER-XRouter:~$ show dns forwarding nameservers
**Nameservers configured for DNS forwarding
209.244.0.3 available via 'optionally configured'
209.244.0.4 available via 'optionally configured'
Nameservers NOT configured for DNS forwarding
192.168.50.1 available via 'dhcp eth0**'

ER-XRouter:~$ configure
[edit]

ER-XRouter# show ?
firewall         interfaces       service          system           traffic-control
[edit]

ER-XRouter# show service ?
dhcp-server  dns          gui          nat          ssh          unms
[edit]

ER-XRouter# show service dns ?
forwarding

[edit]
ER-XRouter# show service dns forwarding ?
cache-size  listen-on   system
[edit]

ER-XRouter# show service dns forwarding name-server
Configuration under specified path is empty
[edit]

Maybe this will help:
https://help.ui.com/hc/en-us/articles/115010913367-EdgeRouter-DNS-Forwarding-Setup-and-Options

Thanks for the compliment,
-Mike
