### ISSUE TITLE
Archive links using Wayback Machine

### ISSUE THREAD

**Issue by nbrewk** [mjp66/Ubiquiti#69]
You’ve included a lot of links for citations and resources. Can I suggest these be linked through the [Wayback Machine](https://archive.org/web/) on archive.org?

This would keep forum posts archived and readable for the foreseeable future, should the  Ubiquiti community interface undergo a redesign and break code snippets. 

——

Sidenote: Thank you for the wonderful guide, and this subsequent rewrite. This is an amazing resource to advance my “hobbyist” networking skills.

**Comment by mjp66** [comment]
I've done this for a couple of really important links, when I updated for the the "Second Edition".
If you would like to submit them here, I'll try and include them in the next release.
Thanks,
-Mike
