### ISSUE TITLE
Chapter 55:  inconsistency found

### ISSUE THREAD

**Issue by kjswanson** [mjp66/Ubiquiti#72]
In this chapter, you instruct the users to add rules based on the backup data that is shown. You then have an exercise for the reader to adjust the ordering of the four rules such that “Allow Ping” rule order changes from #4 to #3.

The inconsistency is that backup data is already in the correct order. 

Side note: 
Firmware bug found, when adding  interfaces in the interfaces tab for a given ruleset.

It appears that in the latest version of the firmware will only show two interfaces in the dialog box no matter how many interfaces are added. The behavior appears to me as: The first interface added will remain as the first added interface always. The second interface will change each time an interface is added. However, when one saves/updates the rule set all of the added interfaces are shown in the interfaces column for the given rule set. 

<img width="1130" alt="Interfaces screen shot" src="https://github.com/mjp66/Ubiquiti/assets/25890709/6debfeb7-b409-43a7-867c-bb9214ae70c9">

**Comment by mjp66** [comment]
Nice catch.
I've fixed the backup data ordering, and added a note about the dialog box limit. Will be in the next release.
Thanks,
-Mike

**Comment by kjswanson** [comment]
No problem!!! Thank you so much for your effort in producing this knowledge
source!

You are a true hero!
