### ISSUE TITLE
No leases from HomeDCHP i config 20230324

### ISSUE THREAD

**Issue by Multiply4998** [mjp66/Ubiquiti#73]
Currently running EdgeRouter X v2.0.9-hotfix.7 
Configured from factory reset following the guide Home-Network Implementation
No Alerts or errors in the log

Problem:
After trying the updated guide the DHCP Server on 192.168.3.x named HomeDHCP does not provide the clients with IP-addresses
IotDCHP and SeparateDHCP works as the should.

Observation:
When DNSMasq is disabled HomeDCHP works but there's then a problem with DNS-forwarding (that can be ugly-solved by adding switch0.1 to the listen-on list)

I tried a few times to follow the excelent guide but then resetted the router and used the config.boot from 20230324 with the same problem. I have also done a step by step configuration following the show configuration commands.txt

**Comment by mjp66** [comment]
Hi,

Ensure you have enabled "Authoritative", see section 31. Verify each DHCP server is set to authoritative in your config.

You can try looking up articles in BuckeveNet's Link Farm at
https://community.ui.com/questions/BuckeyeNets-link-farm/d58f154d-8dd7-48a3-aba1-5d35fb84c9d2

 Maybe you could export your config and compare it to my posted reference config.

It looks like you already tried directly loading the reference config, which also failed for you. Interesting.

You could post your config here, and I can try to compare it. Ensure you sanitize it first, per:
https://help.ui.com/hc/en-us/articles/360012074414
 
You might try stepping back to 2.0.9 hf6 (which is what I am using).

Good Luck,
-Mike

**Comment by Multiply4998** [comment]
Hi Mike, thank you for taking the time to answer me.

I have done some testing today. And my findings are a bit confusing.

I did revert to 2.0.9 hf6 so I had the same starting point. Then I did a file compare between your config.boot with mine. As I mentioned they are identical except for time zone and username/password.

 

I factory reset the router and uploaded the boot.config. 
I tested that I could release and renew the IP-addr on HomeNet to see that the DHCP was functional. I also  successfully pinged router.local

Everything worked fine until I assigned a static address to a device in DHCPHome.

After that the DHCP stopped working and I couldn’t ping router.local and also not google.com from my laptop. But the router could ping google.com.

When releasing the IP-addr could not renew it because the laptop could not contact the DHCP server anymore.

I manually assigned an IP-addr to the laptop and logged in to the router at 192.168.3.1 to get some logs and do some testing.

In the logs I noted warnings about DHCP subnet  is configured on interface eth2a and switch0.6,7,8 but not configured under DNS forwarding listen-on.

 

So I tried adding switch0.1 as Listen Interface for DNS forwarding – and yay now it worked again! But why should assigning an static address mess it up?

 

I did some more testing and found another small thing. On the IOT_Net I couldn’t ping router.local or any device with hostname.iotnet. On page 128 in the guide it says that the two NAT rules for OpenDNS are optional. In the config.boot i copied from you when I looked for the problem the rules are enabled but the DNS server of DHCPIot is set to 192.168.7.1 so it doesn’t work. Disabling the two rules (which I don’t need in my setup) solved the problem.

 

What I really hope for is for you to say I’m wrong and have done some simple error. Because I can’t get my head around why the working setup would stop leasing IP-addr on DHCPHome (the other worked fine) just because I assign a static IP-addr to a device. I have repeated this many times with different devices and different addresses.

 

Best regards and sorry for my bad English, I was born before kids in Sweden learned the language at early age :)
Ron

 

Från: Mike ***@***.***> 
Skickat: den 6 oktober 2023 22:12
Till: mjp66/Ubiquiti ***@***.***>
Kopia: Multiply4998 ***@***.***>; Author ***@***.***>
Ämne: Re: [mjp66/Ubiquiti] No leases from HomeDCHP i config 20230324 (Issue #73)

 

Hi,

Ensure you have enabled "Authoritative", see section 31. Verify each DHCP server is set to authoritative in your config.

You can try looking up articles in BuckeveNet's Link Farm at
https://community.ui.com/questions/BuckeyeNets-link-farm/d58f154d-8dd7-48a3-aba1-5d35fb84c9d2

Maybe you could export your config and compare it to my posted reference config.

It looks like you already tried directly loading the reference config, which also failed for you. Interesting.

You could post your config here, and I can try to compare it. Ensure you sanitize it first, per:
https://help.ui.com/hc/en-us/articles/360012074414

You might try stepping back to 2.0.9 hf6 (which is what I am using).

Good Luck,
-Mike

**Comment by mjp66** [comment]
Hi,
I have never seen and don't know why your DHCP server is stopping.
Glad you at-least know what is causing it to halt.
If you need more answers, you can always post on the Ubiquiti Community.
-Mike
